# Generated by Django 6.1.1 on 2026-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='0339-8770001', max_length=50)),
                ('whatsapp_number', models.CharField(default='923398770001', max_length=50)),
                ('city', models.CharField(default='Rahim Yar Khan', max_length=100)),
                ('timings_weekdays', models.CharField(default='Mon–Sat 9:00 AM – 6:00 PM', max_length=200)),
                ('timings_sunday', models.CharField(default='Sunday Closed', max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'degree_title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon_name', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('category', models.CharField(choices=[('male_health', 'Male Reproductive Health'), ('pediatrics', 'Pediatrics'), ('diabetes', 'Diabetes')], max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
